name: Init repo
on: [push]

jobs:
  rename-project:
    if: ${{ !contains (github.repository, 'gladier-client-template') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false 
          fetch-depth: 0
          github_token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}
        
      - name: Rename the project
        run: |
          .github/workflows/rename_project.sh ${{ github.repository }}
              
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "✅ Ready to clone and code."
          push_options: --force

